[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
myepicproject = "BrqsNiwWpiE8qUK6dSJtErk56C9E6tCdgaijGkJSbPLf"

[registry]
url = "https://api.apr.dev"

# [registry]
# url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"